version: "3.9"
services:
  rumput:
    build: .
    container_name: rumput
    restart: unless-stopped
    ports:
      - "7500:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules